export const GUIDES = [
  {
    slug: "event-budget-blueprint",
    title: "The Event Budget Blueprint",
    subtitle: "Stop guessing. Start planning with numbers that actually work.",
    description: "The exact budget breakdown template used by professional event planners for 50–300 person events. No fluff — just the math.",
    tags: ["Mid-Sized Events", "Budgeting", "All Vendors"],
    readTime: "12 min read",
    pages: 18,
    price: "Free",
    coverEmoji: "💰",
    theme: {
      bg: "#FFFBEE",
      surface: "#FFF7DC",
      accent: "#B8860B",
      accentSoft: "rgba(184,134,11,0.1)",
      text: "#2C1A0E",
      muted: "#8B6914",
      heading: "#1A0F02",
      tag: "#FFF0B3",
      tagText: "#8B6200",
      name: "amber-gold",
    },
    teaser: {
      hook: "Most events go over budget — not because people spend too much, but because they allocate wrong from the start.",
      preview_sections: [
        {
          heading: "The Golden Ratio for Events",
          content: "Event professionals use a 40-25-20-15 split. Catering takes 40%, decoration 25%, photography/entertainment 20%, and logistics 15%. Most people flip the decoration and catering numbers and wonder why food feels underwhelming.",
        },
        {
          heading: "The #1 Budget Mistake",
          content: "Booking your decorator first. Decorators expand to fill whatever budget you give them. Book your caterer first — it anchors your entire spend and forces realistic numbers everywhere else.",
        },
      ],
      tease_line: "What's inside: Full allocation tables for ₹50K / ₹1L / ₹3L / ₹5L+ events, vendor negotiation scripts, and a live calculator you can fill in right now...",
    },
    sections: [
      {
        type: "intro",
        heading: "Why 73% of Events Overspend",
        content: "The culprit isn't extravagance — it's sequencing. This guide walks you through the exact order to book, negotiate, and confirm vendors so you never get a surprise invoice.",
      },
      {
        type: "table",
        heading: "Budget Allocation by Event Size",
        caption: "Recommended percentage split — adjust based on your priorities",
        headers: ["Category", "₹50,000", "₹1,00,000", "₹3,00,000", "₹5,00,000+"],
        rows: [
          ["🍽️ Catering", "₹20,000 (40%)", "₹40,000 (40%)", "₹1,20,000 (40%)", "₹2,00,000 (40%)"],
          ["🎀 Decoration", "₹12,500 (25%)", "₹25,000 (25%)", "₹75,000 (25%)", "₹1,25,000 (25%)"],
          ["📸 Photography", "₹8,000 (16%)", "₹18,000 (18%)", "₹54,000 (18%)", "₹90,000 (18%)"],
          ["🎵 DJ / Music", "₹5,000 (10%)", "₹10,000 (10%)", "₹30,000 (10%)", "₹50,000 (10%)"],
          ["📦 Logistics", "₹4,500 (9%)", "₹7,000 (7%)", "₹21,000 (7%)", "₹35,000 (7%)"],
        ],
      },
      {
        type: "tips",
        heading: "5 Negotiation Scripts That Actually Work",
        tips: [
          { label: "The Bundle Ask", text: '"If we confirm today, can you match ₹X for the full package?" — Works 60% of the time on decorators.' },
          { label: "The Comparison Close", text: '"We have a similar quote from another vendor at ₹Y. Can you do better on value?" — Don\'t lie, compare genuinely.' },
          { label: "The Off-Peak Ask", text: '"Is your pricing different for weekdays / non-peak months?" — Can save 15–25%.' },
          { label: "The Add-On Instead", text: '"Can\'t reduce price — can you add [extra hour / extra item]?" — Vendors find this easier than cutting rates.' },
          { label: "The Referral Promise", text: '"I\'ll refer 3 friends if this goes well." — Genuine, not hollow. Vendors remember this.' },
        ],
      },
      {
        type: "callout",
        heading: "The Buffer Rule",
        content: "Always hold back 8–10% of your budget as a buffer. Not for upgrades — for the unexpected. Cake delivery delay? Extra chairs needed? Overtime charges? Your buffer handles it without stress.",
        highlight: true,
      },
      {
        type: "checklist",
        heading: "Pre-Booking Financial Checklist",
        items: [
          "Get all vendor quotes in writing (WhatsApp screenshot = valid)",
          "Confirm what's NOT included (setup time, travel, breakdown)",
          "Clarify cancellation policy before paying advance",
          "Pay advances via UPI and keep all receipts",
          "Set a final confirm deadline 7 days before event",
          "Confirm headcount with caterer 3 days before",
          "Keep ₹500–1000 cash for day-of tips to staff",
        ],
      },
      {
        type: "breakdown",
        heading: "Real Example: 100-Person Birthday, ₹1.2L Total",
        items: [
          { label: "Caterer (dinner buffet, 100 pax)", amount: "₹48,000", note: "₹480/person, includes serving staff" },
          { label: "Decorator (balloon + draping theme)", amount: "₹28,000", note: "Setup + breakdown included" },
          { label: "Photographer (4 hrs candid)", amount: "₹20,000", note: "400 edited photos delivered in 7 days" },
          { label: "DJ (3 hrs + lights)", amount: "₹12,000", note: "Sound system included" },
          { label: "Cake (2-tier fondant)", amount: "₹4,500", note: "From caterer, bundled" },
          { label: "Invitation cards (50 printed)", amount: "₹1,800", note: "Premium matte finish" },
          { label: "Buffer / misc", amount: "₹5,700", note: "Used ₹2,200 — returned rest to savings" },
        ],
      },
    ],
  },

  {
    slug: "corporate-event-playbook",
    title: "The Corporate Event Playbook",
    subtitle: "From brief to applause — a field guide for events that actually impress.",
    description: "Everything a corporate event manager needs for 50–500 person events: vendor matrix, timeline, engagement strategies, and post-event follow-up.",
    tags: ["Corporate", "50-500 Guests", "All Vendors"],
    readTime: "15 min read",
    pages: 22,
    price: "Free",
    coverEmoji: "🏢",
    theme: {
      bg: "#F2F5F9",
      surface: "#E8EEF6",
      accent: "#1A4A8A",
      accentSoft: "rgba(26,74,138,0.08)",
      text: "#1A2840",
      muted: "#4A6080",
      heading: "#0D1C30",
      tag: "#DCEAF8",
      tagText: "#1A4A8A",
      name: "corporate-navy",
    },
    teaser: {
      hook: "A corporate event is a meeting in disguise. The best ones don't feel like work — they feel like a moment people talk about for months.",
      preview_sections: [
        {
          heading: "The 3-Month Planning Ladder",
          content: "Month 3 before: Lock venue and caterer. Month 2 before: Confirm entertainment, photography, AV. Month 1 before: Send invites, confirm dietary needs, run dress rehearsal. Week before: Confirm all vendors, prepare run sheet. Day before: Brief team, confirm arrival times.",
        },
        {
          heading: "Why Corporate Events Fail",
          content: "Poor transitions. Not bad food, not bad decor — dead time between segments where people check their phones. Every gap >7 minutes without activity = engagement lost. This guide shows how to design a zero-dead-time agenda.",
        },
      ],
      tease_line: "What's inside: Full vendor matrix by budget tier, run sheet template, dietary restriction handling, 20 team engagement activities, and a post-event ROI framework...",
    },
    sections: [
      {
        type: "timeline",
        heading: "The Zero-Stress Planning Timeline",
        steps: [
          { time: "3 Months Out", tasks: ["Confirm budget with management", "Book venue (non-negotiable — everything else follows)", "Finalize guest count (±20% buffer)", "Brief caterer on dietary needs upfront"] },
          { time: "2 Months Out", tasks: ["Book photographer + videographer", "Confirm AV setup (mic, projector, screen)", "Brief entertainment/DJ on company culture", "Send save-the-date to attendees"] },
          { time: "1 Month Out", tasks: ["Send formal invites with RSVP link", "Share agenda with all speakers/performers", "Confirm vendor arrival and breakdown times", "Order branded stationery (nameboards, banners)"] },
          { time: "1 Week Out", tasks: ["Create run sheet (minute-by-minute)", "Brief MC or internal host", "Confirm headcount with caterer", "Prepare contingency: backup AV, extra chairs"] },
          { time: "Day Before", tasks: ["Walk venue with team", "Test all AV equipment", "Place name cards, signage, welcome kits", "Confirm vendor arrival times via WhatsApp"] },
        ],
      },
      {
        type: "table",
        heading: "Vendor Budget Matrix by Event Size",
        caption: "Approximate costs for Delhi NCR — may vary by vendor quality",
        headers: ["Vendor", "₹1L Event (50 pax)", "₹3L Event (150 pax)", "₹7L Event (300 pax)"],
        rows: [
          ["🍽️ Caterer", "₹40,000", "₹1,10,000", "₹2,50,000"],
          ["🎀 Decorator", "₹20,000", "₹60,000", "₹1,40,000"],
          ["📸 Photographer", "₹15,000", "₹30,000", "₹55,000"],
          ["🎵 Entertainment", "₹10,000", "₹25,000", "₹60,000"],
          ["📋 Stationery", "₹5,000", "₹12,000", "₹25,000"],
          ["🖥️ AV / Tech", "₹10,000", "₹18,000", "₹35,000"],
        ],
      },
      {
        type: "tips",
        heading: "20 Engagement Activities (Ranked by Effort)",
        tips: [
          { label: "Zero Effort", text: "Live poll via Mentimeter or Slido during talks — instant participation, no prep." },
          { label: "Low Effort", text: "Photo wall with branded frame — guests take selfies, generates social content." },
          { label: "Low Effort", text: "Lucky draw from RSVP list — announce at the end, keeps attendance till close." },
          { label: "Medium Effort", text: "Team trivia via WhatsApp group — 10 questions sent during the event, prizes for top 3." },
          { label: "Medium Effort", text: "Live caricature artist — guests queue during breaks, leave with a personalized sketch." },
          { label: "High Impact", text: "Open mic segment — 3-minute slot for employees to share a story, talent, or thank-you." },
        ],
      },
      {
        type: "callout",
        heading: "The Dietary Checklist You Cannot Skip",
        content: "Collect dietary restrictions in your RSVP form — not over email after. Categories to cover: Vegetarian, Vegan, Jain, Gluten-free, Nut allergy, Lactose intolerant, Halal. Label every dish on the buffet. Have your caterer prepare 15% extra of vegetarian options.",
        highlight: true,
      },
    ],
  },

  {
    slug: "house-party-handbook",
    title: "The House Party Handbook",
    subtitle: "Throw the best party on the block — without spending like it.",
    description: "The no-nonsense guide to throwing an unforgettable house party for 20–80 people. Budget breakdowns, music hacks, space setup, and the games that actually get people going.",
    tags: ["House Party", "DIY", "Budget Tips"],
    readTime: "10 min read",
    pages: 14,
    price: "Free",
    coverEmoji: "🎉",
    theme: {
      bg: "#FFF4ED",
      surface: "#FFE8D6",
      accent: "#C74B14",
      accentSoft: "rgba(199,75,20,0.09)",
      text: "#2C1205",
      muted: "#8B4520",
      heading: "#1A0800",
      tag: "#FFD5B8",
      tagText: "#8B3000",
      name: "warm-orange",
    },
    teaser: {
      hook: "The best house parties aren't the most expensive ones. They're the ones where the host knew exactly what to cut — and what to go all in on.",
      preview_sections: [
        {
          heading: "The ₹5,000 Party Paradox",
          content: "You can throw a genuinely great party for 30 people with ₹5,000. The trick: spend ₹2,000 on food (make it good), ₹1,500 on a curated Spotify playlist through a Bluetooth speaker, ₹1,000 on balloon decor (floor-level clusters look premium), and ₹500 on themed cups + plates. What you save: a DJ you don't need, catering you don't need, decor that fills space but adds nothing.",
        },
        {
          heading: "The One Thing That Makes or Breaks It",
          content: "Music transitions. A playlist with no energy drops — songs that naturally build into each other — keeps the vibe alive without a DJ. We've included a link to a Spotify playlist template in the full guide.",
        },
      ],
      tease_line: "What's inside: Full ₹5K / ₹10K / ₹20K party budgets, 15 DIY decor ideas, the games matrix (indoor/outdoor, 20/50/80 people), food ideas that work without a caterer...",
    },
    sections: [
      {
        type: "breakdown",
        heading: "Three Budget Parties — Fully Costed",
        note: "Costs based on Delhi NCR, self-purchased from local markets",
        items: [
          { label: "₹5,000 Party (30 guests) — The Minimalist", amount: "", note: "Food: ₹2,000 | Drinks: ₹1,000 | Decor: ₹1,200 | Misc: ₹800" },
          { label: "₹10,000 Party (50 guests) — The Social One", amount: "", note: "Food: ₹3,500 | Drinks: ₹2,500 | Decor: ₹2,500 | Games: ₹1,000 | Misc: ₹500" },
          { label: "₹20,000 Party (80 guests) — The Full Send", amount: "", note: "Caterer (light snacks): ₹8,000 | Bar setup: ₹4,000 | Decorator: ₹4,500 | Music (DJ mini): ₹2,500 | Misc: ₹1,000" },
        ],
      },
      {
        type: "tips",
        heading: "15 DIY Decor Ideas Under ₹200 Each",
        tips: [
          { label: "Balloon Clusters", text: "Floor-level clusters of 5–7 balloons in 2 colors look like a decorator did it. Buy from Lajpat Nagar, Delhi — 50 balloons for ₹150." },
          { label: "Fairy Light Canopy", text: "Drape two strings of fairy lights diagonally across the ceiling. Instant vibe transformation — ₹150 on Meesho." },
          { label: "Photo Wall", text: "Print 15 photos of the guest of honor, string them with clips on jute rope. Backdrop + activity + memory in one." },
          { label: "Floating Table Numbers", text: "Balloon with a number written in a gold marker. No stands, no printing — ₹10 each." },
          { label: "Bar Cart Display", text: "Even if it's just a side table — arrange drinks with labels facing out, add a small plant. Guests will photograph it." },
        ],
      },
      {
        type: "table",
        heading: "Games Matrix — What Works for Which Group",
        caption: "Pick games based on your crowd type, not just headcount",
        headers: ["Game", "Group Size", "Energy Level", "Works Best For"],
        rows: [
          ["Antakshari", "20–80", "🔥 High", "Family / Mixed age groups"],
          ["Tambola (Housie)", "20–80", "😊 Medium", "All ages, corporate, family"],
          ["Beer Pong / Variants", "10–30", "🔥🔥 Very High", "College / Young adults"],
          ["Dumb Charades", "10–40", "🔥 High", "Friends, close-knit groups"],
          ["Photo Scavenger Hunt", "20–80", "😊 Medium", "Corporate, mixed groups"],
          ["Truth or Dare Cards", "10–20", "🔥 High", "Close friends only"],
          ["Name That Tune", "20–60", "😊 Medium", "All ages with good music taste"],
        ],
      },
    ],
  },

  {
    slug: "wedding-hamper-guide",
    title: "The Wedding Gift Hamper Guide",
    subtitle: "30 hamper ideas that guests actually keep — and talk about.",
    description: "A curated guide to creating personalised wedding gift hampers and return gifts across three budget tiers. Includes sourcing, packaging, and personalisation ideas for Delhi NCR.",
    tags: ["Wedding", "Gift Hampers", "Return Gifts"],
    readTime: "11 min read",
    pages: 16,
    price: "Free",
    coverEmoji: "🎁",
    theme: {
      bg: "#FEF5F8",
      surface: "#FCE8EE",
      accent: "#A03050",
      accentSoft: "rgba(160,48,80,0.08)",
      text: "#2C0D1A",
      muted: "#7A3A50",
      heading: "#1A0510",
      tag: "#FADADF",
      tagText: "#A03050",
      name: "bridal-rose",
    },
    teaser: {
      hook: "The return gift is the last memory a guest takes home from your wedding. Make it one they don't leave behind at the venue.",
      preview_sections: [
        {
          heading: "Why Most Return Gifts Get Left Behind",
          content: "Generic dry fruit boxes, plastic trinkets, and branded diaries — guests leave them on chairs. The ones that travel home are personalised, practical, or genuinely beautiful. This guide shows you the exact items that have the highest 'take-home rate' from weddings in the last 3 years.",
        },
        {
          heading: "The 3 Rules of a Great Hamper",
          content: "Rule 1 — One hero item: every hamper needs one thing the guest didn't expect. Rule 2 — Useful beats decorative: candles, skincare, snacks outlast photo frames. Rule 3 — Presentation is half the product: a ₹300 hamper in a jute bag with a ribbon looks more premium than a ₹600 hamper in a plastic box.",
        },
      ],
      tease_line: "What's inside: 30 hamper ideas across ₹150/₹400/₹800 tiers, packaging guide, personalisation text templates, Delhi NCR sourcing directory...",
    },
    sections: [
      {
        type: "tips",
        heading: "Tier 1 — ₹100–200 Per Hamper (Budget but Beautiful)",
        tips: [
          { label: "Miniature Plant Hamper", text: "Succulent in a terracotta pot + personalised note. ₹120. Guests keep the plant for months. Sources: Mehrauli nurseries, Delhi." },
          { label: "Tea + Honey Set", text: "2 herbal tea bags + a honey sachet in a kraft paper box. ₹150. Feels premium, universally loved." },
          { label: "Scented Candle", text: "Single wick soy candle in a glass jar. ₹180. Feels luxe, takes zero effort from the guest." },
          { label: "Artisan Chocolates", text: "3-piece artisan chocolate box with custom sticker label. ₹160. Order in bulk from Hauz Khas vendors." },
          { label: "Spice Kit", text: "3 miniature spice jars (saffron, cardamom, rose petals) in a jute pouch. ₹175. Travel-friendly, practical." },
        ],
      },
      {
        type: "tips",
        heading: "Tier 2 — ₹350–500 Per Hamper (The Sweet Spot)",
        tips: [
          { label: "Skincare Starter Set", text: "Face mist + lip balm + mini moisturiser in a fabric pouch. ₹420. Works for all genders. Source: Nykaa B2B or Lajpat market." },
          { label: "Gourmet Snack Box", text: "Flavoured makhana + trail mix + multigrain crackers in a custom printed box. ₹380. Consumed at home, remembered." },
          { label: "Personalised Stationery Set", text: "Notebook + pen + 2 bookmarks with event date. ₹350. Professional look, high perceived value." },
          { label: "Wellness Hamper", text: "Tulsi honey + immunity kadha + herbal tea. ₹450. Trending post-2022, feels thoughtful." },
          { label: "Coffee Lover Box", text: "2 specialty coffee sachets + a coaster with your event artwork. ₹400. Grows in popularity each year." },
        ],
      },
      {
        type: "callout",
        heading: "The Personalisation Formula",
        content: 'Every hamper should have one personalised element — it doesn\'t have to cost extra. A sticker label with "With love from [Name] & [Name], [Date]" on any item elevates the whole hamper. Print 100 stickers for ₹200 total at any local print shop.',
        highlight: true,
      },
      {
        type: "checklist",
        heading: "Hamper Logistics Checklist",
        items: [
          "Order 10–15% extra (last-minute guest additions are guaranteed)",
          "Pack 3 days before wedding — not the night before",
          "Label hampers by guest category: family / friends / VIP",
          "Assign 2 people specifically for hamper distribution",
          "Place hampers on chairs before guests arrive (not during dinner)",
          "For destination weddings: choose non-liquid, non-fragile items only",
        ],
      },
    ],
  },

  {
    slug: "decor-on-a-budget",
    title: "Decor on a Budget",
    subtitle: "Make any space look like a professional decorated it — without the bill.",
    description: "The insider guide to event decoration across all budgets. Covers trending themes, rental vs buy decisions, lighting hacks, and the 3 elements that change everything.",
    tags: ["Decor", "All Events", "DIY + Vendor"],
    readTime: "13 min read",
    pages: 20,
    price: "Free",
    coverEmoji: "🎨",
    theme: {
      bg: "#F7EFE5",
      surface: "#EFE0CC",
      accent: "#7B3F18",
      accentSoft: "rgba(123,63,24,0.08)",
      text: "#2C1A0A",
      muted: "#7A5030",
      heading: "#1A0E04",
      tag: "#E8D0B8",
      tagText: "#5A2E0A",
      name: "terracotta",
    },
    teaser: {
      hook: "Lighting is the single most underrated element in event decor. A room with average decor and great lighting looks stunning. Great decor in bad lighting looks forgettable.",
      preview_sections: [
        {
          heading: "The 3 Elements That Change Everything",
          content: "1. Lighting — Warm fairy lights or uplighting transform any space. Cost: ₹1,500–5,000 for rental. 2. Entry point — Whatever guests see first is what they remember. Spend 30% of your decor budget at the entrance. 3. One focal wall — A single backdrop wall with balloons, draping, or a floral arch anchors every photo and justifies everything else.",
        },
        {
          heading: "Rent vs Buy — The Rule",
          content: "Rent anything used for less than 3 events. Buy only what you'll reuse: fairy lights, balloon pumps, table runners, and reusable signage frames. Renting in Delhi NCR typically costs 60–70% less than buying for one-time use.",
        },
      ],
      tease_line: "What's inside: 2025 trending themes with vendor cost estimates, DIY vs vendor comparison chart, lighting guide, full balloon decor tutorial, Delhi NCR rental directory...",
    },
    sections: [
      {
        type: "tips",
        heading: "Top 6 Trending Themes for 2025",
        tips: [
          { label: "Celestial / Midnight Garden", text: "Deep blue + silver + fairy lights + faux florals. Works for birthdays, anniversaries, corporate galas. Budget: ₹18,000–40,000 for a 50-pax hall." },
          { label: "Pastel Minimalist", text: "Sage green + blush + white + greenery. Clean, Instagram-ready, low clutter. Budget: ₹12,000–25,000. Extremely popular for baby showers and bridal functions." },
          { label: "Retro Bollywood", text: "Marigold garlands + vintage film posters + fairy lights + warm tones. Budget-friendly, highly photogenic. ₹8,000–18,000." },
          { label: "Jungle / Botanical", text: "Lush greenery, tropical leaves, rattan furniture. Works for outdoor events, terrace parties. Budget: ₹15,000–35,000." },
          { label: "Neon Glow Party", text: "Black lights + neon balloons + UV reactive face paint stations. High energy, perfect for corporate and college events. ₹20,000–45,000." },
          { label: "Earthy Rustic", text: "Jute, wood, terracotta, dried flowers. The most sustainable option — many props are reusable. ₹10,000–22,000." },
        ],
      },
      {
        type: "table",
        heading: "DIY vs Vendor: Where to Spend, Where to Save",
        caption: "Based on effort, visual impact, and average Delhi NCR vendor cost",
        headers: ["Decor Element", "DIY Cost", "Vendor Cost", "Verdict"],
        rows: [
          ["Balloon clusters", "₹300–600", "₹2,000–5,000", "DIY saves most here — YouTube tutorials work"],
          ["Backdrop / draping", "₹800–1,500", "₹4,000–12,000", "Vendor — technique matters enormously"],
          ["Table centerpieces", "₹200–500/table", "₹600–1,500/table", "DIY for simple events; vendor for weddings"],
          ["Fairy light canopy", "₹600–1,200", "₹3,000–6,000", "DIY easily — buy lights once, reuse forever"],
          ["Floral arch", "₹1,500–3,000", "₹6,000–20,000", "Vendor — faux florals need professional assembly"],
          ["Entrance setup", "₹1,000–2,500", "₹5,000–15,000", "Vendor — first impression isn't where to cut"],
        ],
      },
      {
        type: "callout",
        heading: "The 70/30 Lighting Rule",
        content: "Spend 70% of your lighting budget on warm ambient light (fairy lights, uplighting) and 30% on focused accent light (spotlights on the cake table, backdrop). Cold white tube lights kill any event atmosphere instantly — always ask your venue to switch them off.",
        highlight: true,
      },
      {
        type: "checklist",
        heading: "Decor Day-Of Checklist",
        items: [
          "Confirm decorator arrival time (should be 3–4 hrs before guests)",
          "Do a final walkthrough 1 hour before guests arrive",
          "Check all lighting is working (carry extra bulbs)",
          "Ensure focal wall / backdrop is centered and well-lit",
          "Remove any packaging, boxes, or excess props from visible areas",
          "Assign one person to manage decor breakdown post-event",
          "Photograph the setup before guests arrive for your records",
        ],
      },
    ],
  },
];
